### ISSUE TITLE
"SassError: Undefined variable" while using variables from src/css/quasar.variables.scss in a component

### ISSUE THREAD

**Issue by jclaveau** [badsaarow/quasar2-storybook-boilerplate#47]
Using Sass variables like $primary directly in a component like below works in Quasar but throws `SassError: Undefined variable` in Storybook:
```html
<style lang="scss">
// This import is required only in Storybook
@import "src/css/quasar.variables.scss";

.q-field--filled .q-field__control::before {
        background-color: rgba( $primary-custom , 0.8);
	border-bottom: 1px solid $glass-green-dark;
}
```

Someone reported the same problem here:
https://github.com/quasarframework/quasar/issues/11654

**Comment by badsaarow** [comment]
@jclaveau 

Storybook should use compiled variables of Quasar not direct.

Quasar's scss variables compiled to CSS,  then storybook use quasar component.
So, to use quasar's scss variables, should use like upper commit example.

```css
<style>
.q-btn .q-btn--actionable::before {
  background-color: rgba(var(--q-accent), 0.8);
  border-bottom: 1px solid var(--q-accent);
}
</style>
```
